### PR TITLE
[HOPSWORKS-937] Adjust Cgroup configuration to account for longer Cgroup deletion and make CPU utilization configurable

### PR DESCRIPTION
**Pull request by robzor92**

### CODE REVIEW

**Comment by robzor92** [comment]
@SirOibaf want me to run testing for this? Deployed this on my VM and it works.

**Comment by robzor92** [comment]
@SirOibaf set it back to 100

**Comment by robzor92** [comment]
https://github.com/logicalclocks/hops-testing/pull/292

**Comment by robzor92** [comment]
@SirOibaf please review and merge if ok.

**Comment by SirOibaf** [comment]
LGMT

**Pull request merged**
